//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceDashboard.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinanceDashboard.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///   {
        ///      &quot;Balance&quot;:&quot;69.69&quot;,
        ///      &quot;Abreviation&quot;:&quot;RON&quot;,
        ///      &quot;Symbol&quot;:&quot;pack://application:,,,/FinanceDashboard;component/Resources/Files/Romania.jpg&quot;,
        ///      &quot;Code&quot;:&quot;RO&quot;,
        ///      &quot;Name&quot;:&quot;Romanian Leu&quot;,
        ///      &quot;Transactions&quot;:[
        ///         {
        ///            &quot;Symbol&quot;:&quot;pack://application:,,,/FinanceDashboard;component/Resources/Files/Groceries.png&quot;,
        ///            &quot;VendorName&quot;:&quot;Magazin Mixt&quot;,
        ///            &quot;Date&quot;:&quot;2019-07-26T00:00:00&quot;,
        ///            &quot;Price&quot;:&quot;2.50&quot;
        ///         }
        ///      ],
        ///      &quot;NearbyRewards&quot;:[
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///   {
        ///      &quot;Title&quot;:&quot;Standard&quot;,
        ///      &quot;Subtitle&quot;:&quot;Free&quot;,
        ///      &quot;Image&quot;:&quot;pack://application:,,,/FinanceDashboard;component/Resources/Files/RevolutStandard.png&quot;,
        ///      &quot;Description&quot;:&quot;Whether you&apos;re looking to save money spending abroad or sticking to your budget with our built-in budgeting, get more from your money with our Standard account.&quot;,
        ///      &quot;Cardcolor&quot;:&quot;#836DBA&quot;,
        ///      &quot;Benefits&quot;:[
        ///         {
        ///            &quot;Icon&quot;:&quot;Money&quot;,
        ///            &quot;Explanation&quot;:&quot;No fee ATM withdrawals within limits&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Plans {
            get {
                return ResourceManager.GetString("Plans", resourceCulture);
            }
        }
    }
}
